import "server-only";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
} from "docx";
import { pointText, metaLine, type ExportData } from "./shared";

/** Render a notes document to a .docx buffer with proper heading levels. */
export async function renderNoteDocx(data: ExportData): Promise<Buffer> {
  const { notes } = data;
  const children: Paragraph[] = [];

  // Header
  children.push(
    new Paragraph({
      heading: HeadingLevel.TITLE,
      children: [new TextRun({ text: data.lectureTitle, bold: true })],
    }),
    new Paragraph({
      children: [new TextRun({ text: metaLine(data), italics: true, color: "666666" })],
    }),
    new Paragraph({ text: "" })
  );

  // Summary
  if (notes.summary) {
    children.push(
      new Paragraph({
        children: [new TextRun({ text: "SUMMARY", bold: true, color: "9A7B34", size: 18 })],
      }),
      new Paragraph({ children: [new TextRun(notes.summary)] }),
      new Paragraph({ text: "" })
    );
  }

  // Sections (H1) → bullets, subsections (H2) → indented bullets
  (notes.sections ?? []).forEach((section, i) => {
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        text: `${(i + 1).toString().padStart(2, "0")}  ${section.heading}`,
      })
    );
    (section.points ?? []).forEach((p) => {
      children.push(new Paragraph({ text: pointText(p), bullet: { level: 0 } }));
    });
    (section.subsections ?? []).forEach((sub) => {
      children.push(
        new Paragraph({ heading: HeadingLevel.HEADING_2, text: sub.heading })
      );
      (sub.points ?? []).forEach((p) => {
        children.push(
          new Paragraph({ text: pointText(p), bullet: { level: 1 } })
        );
      });
    });
  });

  // Key concepts — bold term, definition beneath
  if ((notes.keyConcepts ?? []).length > 0) {
    children.push(
      new Paragraph({ text: "Key Concepts", heading: HeadingLevel.HEADING_1 })
    );
    notes.keyConcepts.forEach((c) => {
      children.push(
        new Paragraph({ children: [new TextRun({ text: c.term, bold: true })] }),
        new Paragraph({ children: [new TextRun({ text: c.definition, color: "555555" })] })
      );
    });
  }

  children.push(
    new Paragraph({ text: "" }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: "Generated by Atlas", color: "999999", size: 16 })],
    })
  );

  const doc = new Document({ sections: [{ children }] });
  return Buffer.from(await Packer.toBuffer(doc));
}
