// Embeds the bundled Geist woff2 files as base64 data URLs so the render never
// depends on a font server or the network (the render environment can't fetch
// Google Fonts, and Remotion's static-file serving 404'd here). Output is a
// generated module consumed by src/fonts.ts.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const fontsDir = join(here, "..", "public", "fonts");

const files = [
  { family: "Geist", weight: "400", file: "Geist-Regular.woff2" },
  { family: "Geist", weight: "500", file: "Geist-Medium.woff2" },
  { family: "Geist", weight: "600", file: "Geist-SemiBold.woff2" },
  { family: "Geist", weight: "700", file: "Geist-Bold.woff2" },
  { family: "Geist Mono", weight: "400", file: "GeistMono-Regular.woff2" },
  { family: "Geist Mono", weight: "500", file: "GeistMono-Medium.woff2" },
];

const entries = files.map(({ family, weight, file }) => {
  const b64 = readFileSync(join(fontsDir, file)).toString("base64");
  return `  { family: ${JSON.stringify(family)}, weight: ${JSON.stringify(
    weight
  )}, dataUrl: "data:font/woff2;base64,${b64}" }`;
});

const out = `// AUTO-GENERATED by scripts/embed-fonts.mjs — do not edit.
export const EMBEDDED_FONTS = [
${entries.join(",\n")},
];
`;

writeFileSync(join(here, "..", "src", "generated-fonts.ts"), out);
console.log(`Embedded ${files.length} font weights → src/generated-fonts.ts`);
